using System;
using System.Linq;
using System.Text;
using System.Reflection;

namespace FhirDeathRecord
{
    /// <summary>Data helper class for dealing with IJE mortality data. Follows Singleton-esque pattern!</summary>
    public sealed class IJEMortalityData
    {
        private IJEMortalityData() {
        }
        public static IJEMortalityData Instance { get { return Nested.instance; } }
        private class Nested
        {
            static Nested() {}
            internal static readonly IJEMortalityData instance = new IJEMortalityData();
        }

        // <summary>Given a State, Territory, or Province name - return the representative code.</summary>
        public string StateTerritoryProvinceToCode(string state)
        {
            if (state == null)
            {
                return null;
            }
            int index = StateTerritoryProvinceCodes.ToList().FindIndex(t => t.Item1 == state.ToLower());
            return StateTerritoryProvinceCodes[index].Item2.ToUpper();
        }

        // <summary>Given a code - return the representative State, Territory, or Province name.</summary>
        public string CodeToStateTerritoryProvince(string code)
        {
            if (code == null)
            {
                return null;
            }
            int index = StateTerritoryProvinceCodes.ToList().FindIndex(t => t.Item2 == code.ToUpper());
            return StateTerritoryProvinceCodes[index].Item1.ToUpper();
        }

        // <summary>Given a Country name - return the representative code.</summary>
        public string CountryToCode(string state)
        {
            if (state == null)
            {
                return null;
            }
            int index = CountryCodes.ToList().FindIndex(t => t.Item1 == state.ToLower());
            return CountryCodes[index].Item2.ToUpper();
        }

        // <summary>Given a code - return the representative Country name.</summary>
        public string CodeToCountry(string code)
        {
            if (code == null)
            {
                return null;
            }
            int index = CountryCodes.ToList().FindIndex(t => t.Item2 == code.ToUpper());
            return CountryCodes[index].Item1.ToUpper();
        }

        private Tuple<string, string>[] StateTerritoryProvinceCodes =
        {
            Tuple.Create("alabama", "AL"),
            Tuple.Create("alaska", "AK"),
            Tuple.Create("arizona", "AZ"),
            Tuple.Create("arkansas", "AR"),
            Tuple.Create("california", "CA"),
            Tuple.Create("colorado", "CO"),
            Tuple.Create("connecticut", "CT"),
            Tuple.Create("delaware", "DE"),
            Tuple.Create("florida", "FL"),
            Tuple.Create("georgia", "GA"),
            Tuple.Create("hawaii", "HI"),
            Tuple.Create("idaho", "ID"),
            Tuple.Create("illinois", "IL"),
            Tuple.Create("indiana", "IN"),
            Tuple.Create("iowa", "IA"),
            Tuple.Create("kansas", "KS"),
            Tuple.Create("kentucky", "KY"),
            Tuple.Create("louisiana", "LA"),
            Tuple.Create("maine", "ME"),
            Tuple.Create("maryland", "MD"),
            Tuple.Create("massachusetts", "MA"),
            Tuple.Create("michigan", "MI"),
            Tuple.Create("minnesota", "MN"),
            Tuple.Create("mississippi", "MS"),
            Tuple.Create("missouri", "MO"),
            Tuple.Create("montana", "MT"),
            Tuple.Create("nebraska", "NE"),
            Tuple.Create("nevada", "NV"),
            Tuple.Create("new Hampshire", "NH"),
            Tuple.Create("new Jersey", "NJ"),
            Tuple.Create("new Mexico", "NM"),
            Tuple.Create("new York", "NY"),
            Tuple.Create("north Carolina", "NC"),
            Tuple.Create("north Dakota", "ND"),
            Tuple.Create("ohio", "OH"),
            Tuple.Create("oklahoma", "OK"),
            Tuple.Create("oregon", "OR"),
            Tuple.Create("pennsylvania", "PA"),
            Tuple.Create("rhode Island", "RI"),
            Tuple.Create("south Carolina", "SC"),
            Tuple.Create("south Dakota", "SD"),
            Tuple.Create("tennessee", "TN"),
            Tuple.Create("texas", "TX"),
            Tuple.Create("utah", "UT"),
            Tuple.Create("vermont", "VT"),
            Tuple.Create("virginia", "VA"),
            Tuple.Create("washington", "WA"),
            Tuple.Create("west Virginia", "WV"),
            Tuple.Create("wisconsin", "WI"),
            Tuple.Create("wyoming", "WY"),
            Tuple.Create("northern marianas", "MP"),
            Tuple.Create("american samoa", "AS"),
            Tuple.Create("guam", "GU"),
            Tuple.Create("virgin islands", "VI"),
            Tuple.Create("puerto rico", "PR"),
            Tuple.Create("alberta", "AB"),
            Tuple.Create("british columbia", "BC"),
            Tuple.Create("manitoba", "MB"),
            Tuple.Create("new brunswick", "NB"),
            Tuple.Create("newfoundland", "NF"),
            Tuple.Create("nova scotia", "NS"),
            Tuple.Create("northwest territories", "NT"),
            Tuple.Create("nunavut", "NU"),
            Tuple.Create("ontario", "ON"),
            Tuple.Create("prince edward island", "PE"),
            Tuple.Create("quebec", "QC"),
            Tuple.Create("saskatchewan", "SK"),
            Tuple.Create("yukon", "YK")
        };

        private Tuple<string, string>[] CountryCodes =
        {
            Tuple.Create("AFGHANISTAN", "AF"),
            Tuple.Create("AKROTIRI", "AX"),
            Tuple.Create("ÅLAND", "FI"),
            Tuple.Create("ALBANIA", "AL"),
            Tuple.Create("ALGERIA", "AG"),
            Tuple.Create("ANDORRA", "AN"),
            Tuple.Create("ANGOLA", "AO"),
            Tuple.Create("ANGUILLA", "AV"),
            Tuple.Create("ANTARCTICA", "AY"),
            Tuple.Create("ANTIGUA AND BARBUDA", "AC"),
            Tuple.Create("ARGENTINA", "AR"),
            Tuple.Create("ARMENIA", "AM"),
            Tuple.Create("ARUBA", "AA"),
            Tuple.Create("ASHMORE AND CARTIER ISLANDS", "AT"),
            Tuple.Create("AUSTRALIA", "AS"),
            Tuple.Create("AUSTRIA", "AU"),
            Tuple.Create("AZERBAIJAN", "AJ"),
            Tuple.Create("AZORES", "PO"),
            Tuple.Create("BAHAMAS, THE", "BF"),
            Tuple.Create("BAHRAIN", "BA"),
            Tuple.Create("BANGLADESH", "BG"),
            Tuple.Create("BARBADOS", "BB"),
            Tuple.Create("BASSAS DA INDIA", "BS"),
            Tuple.Create("BELARUS", "BO"),
            Tuple.Create("BELGIUM", "BE"),
            Tuple.Create("BELIZE", "BH"),
            Tuple.Create("BENIN", "BN"),
            Tuple.Create("BERMUDA", "BD"),
            Tuple.Create("BHUTAN", "BT"),
            Tuple.Create("BOLIVIA", "BL"),
            Tuple.Create("BONAIRE", "NL"),
            Tuple.Create("BOSNIA AND HERZEGOVINA", "BK"),
            Tuple.Create("BOTSWANA", "BC"),
            Tuple.Create("BOUVET ISLAND", "BV"),
            Tuple.Create("BRAZIL", "BR"),
            Tuple.Create("BRITISH INDIAN OCEAN TERRITORY", "IO"),
            Tuple.Create("BRITISH VIRGIN ISLANDS", "VI"),
            Tuple.Create("BRUNEI", "BX"),
            Tuple.Create("BULGARIA", "BU"),
            Tuple.Create("BURKINA FASO", "UV"),
            Tuple.Create("BURMA", "BM"),
            Tuple.Create("BURUNDI", "BY"),
            Tuple.Create("CAMBODIA", "CB"),
            Tuple.Create("CAMEROON", "CM"),
            Tuple.Create("CANADA", "CA"),
            Tuple.Create("CANTON AND ENDERBERRY ISLANDS", "EQ"),
            Tuple.Create("CAPE VERDE", "CV"),
            Tuple.Create("CAYMAN ISLANDS", "CJ"),
            Tuple.Create("CENTRAL AFRICAN REPUBLIC", "CT"),
            Tuple.Create("CENTRAL AND SOUTHERN LINE ISLANDS", "CL"),
            Tuple.Create("CHAD", "CD"),
            Tuple.Create("CHILE", "CI"),
            Tuple.Create("CHINA", "CH"),
            Tuple.Create("CHRISTMAS ISLAND", "KT"),
            Tuple.Create("CLIPPERTON ISLAND", "IP"),
            Tuple.Create("COCOS (KEELING) ISLANDS", "CK"),
            Tuple.Create("COLOMBIA", "CO"),
            Tuple.Create("COMOROS", "CN"),
            Tuple.Create("CONGO (BRAZZAVILLE)", "CF"),
            Tuple.Create("CONGO (KINSHASA)", "CG"),
            Tuple.Create("COOK ISLANDS", "CW"),
            Tuple.Create("CORAL SEA ISLANDS", "CR"),
            Tuple.Create("COSTA RICA", "CS"),
            Tuple.Create("CÔTE D’IVOIRE", "IV"),
            Tuple.Create("CROATIA", "HR"),
            Tuple.Create("CUBA", "CU"),
            Tuple.Create("CURAÇAO", "UC"),
            Tuple.Create("CYPRUS", "CY"),
            Tuple.Create("CZECH REPUBLIC", "EZ"),
            Tuple.Create("CZECHOSLOVAKIA", "CZ"),
            Tuple.Create("DAHOMEY", "DM"),
            Tuple.Create("DEMOCRATIC REPUBLIC OF THE CONGO", "CG"),
            Tuple.Create("DENMARK", "DA"),
            Tuple.Create("DHEKELIA", "DX"),
            Tuple.Create("DJIBOUTI", "DJ"),
            Tuple.Create("DOMINICA", "DO"),
            Tuple.Create("DOMINICAN REPUBLIC", "DR"),
            Tuple.Create("EAST BERLIN", "EB"),
            Tuple.Create("EAST GERMANY", "GC"),
            Tuple.Create("EAST TIMOR", "TT"),
            Tuple.Create("ECUADOR", "EC"),
            Tuple.Create("EGYPT", "EG"),
            Tuple.Create("EL SALVADOR", "ES"),
            Tuple.Create("ENGLAND", "UK"),
            Tuple.Create("EQUATORIAL GUINEA", "EK"),
            Tuple.Create("ERITREA", "ER"),
            Tuple.Create("ESTONIA", "EN"),
            Tuple.Create("ETHIOPIA", "ET"),
            Tuple.Create("ETOROFU, HABOMAI, KUNASHIRI, AND SHIKOTAN ISLANDS", "PJ"),
            Tuple.Create("EUROPA ISLAND", "EU"),
            Tuple.Create("FALKLAND ISLANDS (ISLAS MALVINAS)", "FK"),
            Tuple.Create("FAROE ISLANDS", "FO"),
            Tuple.Create("FEDERAL REPUBLIC OF GERMANY", "GE"),
            Tuple.Create("FEDERATED STATES OF MICRONESIA", "FM"),
            Tuple.Create("FIJI", "FJ"),
            Tuple.Create("FINLAND", "FI"),
            Tuple.Create("FRANCE", "FR"),
            Tuple.Create("FRENCH GUIANA", "FG"),
            Tuple.Create("FRENCH POLYNESIA", "FP"),
            Tuple.Create("FRENCH SOUTHERN AND ANTARCTIC LANDS", "FS"),
            Tuple.Create("FRENCH TERRITORY OF THE AFFARS AND ISSAS", "FT"),
            Tuple.Create("GABON", "GB"),
            Tuple.Create("GAMBIA, THE", "GA"),
            Tuple.Create("GAZA STRIP", "GZ"),
            Tuple.Create("GEORGIA", "GG"),
            Tuple.Create("GERMAN DEMOCRATIC REPUBLIC", "GC"),
            Tuple.Create("GERMANY", "GM"),
            Tuple.Create("GHANA", "GH"),
            Tuple.Create("GIBRALTAR", "GI"),
            Tuple.Create("GILBERT ISLANDS", "GS"),
            Tuple.Create("GILBERT AND ELLICE ISLANDS", "GN"),
            Tuple.Create("GLORIOSO ISLANDS", "GO"),
            Tuple.Create("GREAT BRITAIN", "UK"),
            Tuple.Create("GREECE", "GR"),
            Tuple.Create("GREENLAND", "GL"),
            Tuple.Create("GRENADA", "GJ"),
            Tuple.Create("GUADELOUPE", "GP"),
            Tuple.Create("GUATEMALA", "GT"),
            Tuple.Create("GUERNSEY", "GK"),
            Tuple.Create("GUINEA", "GV"),
            Tuple.Create("GUINEA-BISSAU", "PU"),
            Tuple.Create("GUYANA", "GY"),
            Tuple.Create("HAITI", "HA"),
            Tuple.Create("HEARD ISLAND AND MCDONALD ISLANDS", "HM"),
            Tuple.Create("HOLY SEE", "VT"),
            Tuple.Create("HONDURAS", "HO"),
            Tuple.Create("HONG KONG", "HK"),
            Tuple.Create("HOWLAND ISLAND", "HQ"),
            Tuple.Create("HUNGARY", "HU"),
            Tuple.Create("ICELAND", "IC"),
            Tuple.Create("INDIA", "IN"),
            Tuple.Create("INDONESIA", "ID"),
            Tuple.Create("IRAN", "IR"),
            Tuple.Create("IRAQ", "IZ"),
            Tuple.Create("IRAQ-SAUDI ARABIA NEUTRAL ZONE", "IY"),
            Tuple.Create("IRELAND", "EI"),
            Tuple.Create("ISLAS MALVINAS", "FK"),
            Tuple.Create("ISLE OF MAN", "IM"),
            Tuple.Create("ISRAEL", "IS"),
            Tuple.Create("ISRAEL-JORDAN DEMILITARIZED ZONE", "IW"),
            Tuple.Create("ISRAEL-SYRIA DEMILITARIZED ZONE", "IU"),
            Tuple.Create("ITALY", "IT"),
            Tuple.Create("IVORY COAST", "IV"),
            Tuple.Create("JAMAICA", "JM"),
            Tuple.Create("JAN MAYEN", "JN"),
            Tuple.Create("JAPAN", "JA"),
            Tuple.Create("JARVIS ISLAND", "DQ"),
            Tuple.Create("JERSEY", "JE"),
            Tuple.Create("JOHNSTON ATOLL", "JQ"),
            Tuple.Create("JORDAN", "JO"),
            Tuple.Create("JUAN DE NOVA ISLAND", "JU"),
            Tuple.Create("KAZAKHSTAN", "KZ"),
            Tuple.Create("KENYA", "KE"),
            Tuple.Create("KIRIBATI", "KR"),
            Tuple.Create("KOREA, NORTH", "KN"),
            Tuple.Create("KOREA, SOUTH", "KS"),
            Tuple.Create("KOSOVO", "KV"),
            Tuple.Create("KUWAIT", "KU"),
            Tuple.Create("KYRGYZSTAN", "KG"),
            Tuple.Create("LAOS", "LA"),
            Tuple.Create("LATVIA", "LG"),
            Tuple.Create("LEBANON", "LE"),
            Tuple.Create("LESOTHO", "LT"),
            Tuple.Create("LIBERIA", "LI"),
            Tuple.Create("LIBYA", "LY"),
            Tuple.Create("LIECHTENSTEIN", "LS"),
            Tuple.Create("LITHUANIA", "LH"),
            Tuple.Create("LUXEMBOURG", "LU"),
            Tuple.Create("MACAU", "MC"),
            Tuple.Create("MACEDONIA", "MK"),
            Tuple.Create("MADAGASCAR", "MA"),
            Tuple.Create("MALAWI", "MI"),
            Tuple.Create("MALAYSIA", "MY"),
            Tuple.Create("MALDIVES", "MV"),
            Tuple.Create("MALI", "ML"),
            Tuple.Create("MALTA", "MT"),
            Tuple.Create("MARSHALL ISLANDS", "RM"),
            Tuple.Create("MARTINIQUE", "MB"),
            Tuple.Create("MAURITANIA", "MR"),
            Tuple.Create("MAURITIUS", "MP"),
            Tuple.Create("MAYOTTE", "MF"),
            Tuple.Create("MEXICO", "MX"),
            Tuple.Create("MICRONESIA, FEDERATED STATES OF", "FM"),
            Tuple.Create("MIDWAY ISLANDS", "MQ"),
            Tuple.Create("MOLDOVA", "MD"),
            Tuple.Create("MONACO", "MN"),
            Tuple.Create("MONGOLIA", "MG"),
            Tuple.Create("MONTENEGRO", "MJ"),
            Tuple.Create("MONTSERRAT", "MH"),
            Tuple.Create("MOROCCO", "MO"),
            Tuple.Create("MOZAMBIQUE", "MZ"),
            Tuple.Create("MYANMAR", "BM"),
            Tuple.Create("NAMIBIA", "WA"),
            Tuple.Create("NAURU", "NR"),
            Tuple.Create("NEPAL", "NP"),
            Tuple.Create("NETHERLANDS", "NL"),
            Tuple.Create("NETHERLANDS ANTILLES", "NT"),
            Tuple.Create("NEVIS", "SC"),
            Tuple.Create("NEW CALEDONIA", "NC"),
            Tuple.Create("NEW HEBRIDES", "NH"),
            Tuple.Create("NEW ZEALAND", "NZ"),
            Tuple.Create("NICARAGUA", "NU"),
            Tuple.Create("NIGER", "NG"),
            Tuple.Create("NIGERIA", "NI"),
            Tuple.Create("NIUE", "NE"),
            Tuple.Create("NORFOLK ISLAND", "NF"),
            Tuple.Create("NORTH KOREA", "KN"),
            Tuple.Create("NORTH VIETNAM", "VN"),
            Tuple.Create("NORWAY", "NO"),
            Tuple.Create("OMAN", "MU"),
            Tuple.Create("PAKISTAN", "PK"),
            Tuple.Create("PALAU", "PS"),
            Tuple.Create("PALMYRA ATOLL", "LQ"),
            Tuple.Create("PANAMA", "PM"),
            Tuple.Create("PANAMA", "PN"),
            Tuple.Create("PANAMA CANAL ZONE", "PQ"),
            Tuple.Create("PAPUA NEW GUINEA", "PP"),
            Tuple.Create("PARACEL ISLANDS", "PF"),
            Tuple.Create("PARAGUAY", "PA"),
            Tuple.Create("PERU", "PE"),
            Tuple.Create("PHILIPPINES", "RP"),
            Tuple.Create("PITCAIRN ISLAND", "PC"),
            Tuple.Create("POLAND", "PL"),
            Tuple.Create("PORTUGAL", "PO"),
            Tuple.Create("QATAR", "QA"),
            Tuple.Create("REPUBLIC OF THE CONGO", "CF"),
            Tuple.Create("REUNION", "RE"),
            Tuple.Create("RHODESIA", "RH"),
            Tuple.Create("ROMANIA", "RO"),
            Tuple.Create("RUSSIA", "RS"),
            Tuple.Create("RWANDA", "RW"),
            Tuple.Create("RYUKYU ISLANDS, SOUTHERN", "YQ"),
            Tuple.Create("SABA", "NL"),
            Tuple.Create("SAINT BARTHÉLEMY", "TB"),
            Tuple.Create("SAINT EUSTATIUS", "NL"),
            Tuple.Create("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "SH"),
            Tuple.Create("SAINT KITTS AND NEVIS", "SC"),
            Tuple.Create("SAINT LUCIA", "ST"),
            Tuple.Create("SAINT MARTIN", "RN"),
            Tuple.Create("SAINT PIERRE AND MIQUELON", "SB"),
            Tuple.Create("SAINT VINCENT AND THE GRENADINES", "VC"),
            Tuple.Create("SAMOA", "WS"),
            Tuple.Create("SAN MARINO", "SM"),
            Tuple.Create("SAO TOME AND PRINCIPE", "TP"),
            Tuple.Create("SAUDI ARABIA", "SA"),
            Tuple.Create("SENEGAL", "SG"),
            Tuple.Create("SERBIA", "RI"),
            Tuple.Create("SERBIA AND MONTENEGRO", "YI"),
            Tuple.Create("SEYCHELLES", "SE"),
            Tuple.Create("SIERRA LEONE", "SL"),
            Tuple.Create("SIKKIM ", "SK"),
            Tuple.Create("SINGAPORE", "SN"),
            Tuple.Create("SINT MAARTEN", "NN"),
            Tuple.Create("SLOVAKIA", "LO"),
            Tuple.Create("SLOVENIA", "SI"),
            Tuple.Create("SOLOMON ISLANDS", "BP"),
            Tuple.Create("SOMALIA", "SO"),
            Tuple.Create("SOUTH AFRICA", "SF"),
            Tuple.Create("SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS", "SX"),
            Tuple.Create("SOUTH KOREA", "KS"),
            Tuple.Create("SOUTH SUDAN", "OD"),
            Tuple.Create("SOUTH VIETNAM", "VS"),
            Tuple.Create("SOUTHERN RHODESIA", "RH"),
            Tuple.Create("SOVIET UNION", "UR"),
            Tuple.Create("SPAIN", "SP"),
            Tuple.Create("SPANISH SAHARA", "SS"),
            Tuple.Create("SPRATLY ISLANDS", "PG"),
            Tuple.Create("SRI LANKA", "CE"),
            Tuple.Create("SUDAN", "SU"),
            Tuple.Create("SURINAME", "NS"),
            Tuple.Create("SVALBARD", "SV"),
            Tuple.Create("SVALBARD AND JAN MAYEN", "JS"),
            Tuple.Create("SWAN ISLANDS", "SQ"),
            Tuple.Create("SWAZILAND", "WZ"),
            Tuple.Create("SWEDEN", "SW"),
            Tuple.Create("SWITZERLAND", "SZ"),
            Tuple.Create("SYRIA", "SY"),
            Tuple.Create("TAHITI", "FP"),
            Tuple.Create("TAIWAN", "TW"),
            Tuple.Create("TAJIKISTAN", "TI"),
            Tuple.Create("TANZANIA", "TZ"),
            Tuple.Create("THAILAND", "TH"),
            Tuple.Create("TIMOR-LESTE", "TT"),
            Tuple.Create("TOGO", "TO"),
            Tuple.Create("TOKELAU", "TL"),
            Tuple.Create("TONGA", "TN"),
            Tuple.Create("TRINIDAD AND TOBAGO", "TD"),
            Tuple.Create("TROMELIN ISLAND", "TE"),
            Tuple.Create("TRUST TERRITORY OF THE PACIFIC ISLANDS", "TQ"),
            Tuple.Create("TUNISIA", "TS"),
            Tuple.Create("TURKEY", "TU"),
            Tuple.Create("TURKMENISTAN", "TX"),
            Tuple.Create("TURKS AND CAICOS ISLANDS", "TK"),
            Tuple.Create("TUVALU", "TV"),
            Tuple.Create("UGANDA", "UG"),
            Tuple.Create("UKRAINE", "UP"),
            Tuple.Create("UNION OF SOVIET SOCIALIST REPUBLICS", "UR"),
            Tuple.Create("UNITED ARAB EMIRATES", "AE"),
            Tuple.Create("UNITED ARAB EMIRATES", "TC"),
            Tuple.Create("UNITED KINGDOM", "UK"),
            Tuple.Create("UNITED STATES", "US"),
            Tuple.Create("UPPER VOLTA", "UV"),
            Tuple.Create("URUGUAY", "UY"),
            Tuple.Create("US MISCELLANEOUS PACIFIC ISLANDS ", "IQ"),
            Tuple.Create("UZBEKISTAN", "UZ"),
            Tuple.Create("VANUATU", "NH"),
            Tuple.Create("VATICAN CITY", "VT"),
            Tuple.Create("VENEZUELA", "VE"),
            Tuple.Create("VIETNAM", "VM"),
            Tuple.Create("VIRGIN ISLANDS, BRITISH", "VI"),
            Tuple.Create("WAKE ISLAND", "WQ"),
            Tuple.Create("WALLIS AND FUTUNA", "WF"),
            Tuple.Create("WEST BANK", "WE"),
            Tuple.Create("WEST BERLIN", "WB"),
            Tuple.Create("WEST GERMANY", "GE"),
            Tuple.Create("WESTERN SAHARA", "WI"),
            Tuple.Create("YEMEN", "YM"),
            Tuple.Create("YEMEN (ADEN)", "YS"),
            Tuple.Create("YEMEN (SANA'A)", "YE"),
            Tuple.Create("YUGOSLAVIA", "YI"),
            Tuple.Create("ZAIRE", "CG"),
            Tuple.Create("ZAMBIA", "ZA"),
            Tuple.Create("ZIMBABWE", "ZI"),
            Tuple.Create("NOT CLASSIFIABLE", "ZZ")
        };
    }
}