// DO NOT EDIT MANUALLY! This file was generated by the script "tools/generate_url_strings_from_VRDR_IG.rb"

namespace VRDR
{
    /// <summary>Profile URLs</summary>
    public static class ProfileURLs
    {
        /// <summary>URL for ParametersForEmergingIssues</summary>
        public const string ParametersForEmergingIssues = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-params-for-emerging-issues";

        /// <summary>URL for DeathDate</summary>
        public const string DeathDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-date";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public const string BirthRecordIdentifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-birth-record-identifier";

        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/UnitOrAptNumber";

        /// <summary>URL for DecedentMilitaryService</summary>
        public const string DecedentMilitaryService = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-military-service";

        /// <summary>URL for CauseOfDeathPathway</summary>
        public const string CauseOfDeathPathway = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-pathway";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetDesignator";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public const string TobaccoUseContributedToDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-tobacco-use-contributed-to-death";

        /// <summary>URL for DecedentAge</summary>
        public const string DecedentAge = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-age";

        /// <summary>URL for BypassEditFlag</summary>
        public const string BypassEditFlag = "http://hl7.org/fhir/us/vrdr/StructureDefinition/BypassEditFlag";

        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDateTime";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public const string NVSSSexAtDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/NVSS-SexAtDeath";

        /// <summary>URL for CodedContentBundle</summary>
        public const string CodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coded-content-bundle";

        /// <summary>URL for MannerOfDeath</summary>
        public const string MannerOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manner-of-death";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public const string InputRaceAndEthnicity = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-input-race-and-ethnicity";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public const string CauseOfDeathPart2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part2";

        /// <summary>URL for DateYear</summary>
        public const string DateYear = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Year";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PreDirectional";

        /// <summary>URL for DecedentFather</summary>
        public const string DecedentFather = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-father";

        /// <summary>URL for DecedentEducationLevel</summary>
        public const string DecedentEducationLevel = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-education-level";

        /// <summary>URL for AuxiliaryStateIdentifier1</summary>
        public const string AuxiliaryStateIdentifier1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier1";

        /// <summary>URL for DispositionLocationReference</summary>
        public const string DispositionLocationReference = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DispositionLocationReference";

        /// <summary>URL for SurgeryDate</summary>
        public const string SurgeryDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-surgery-date";

        /// <summary>URL for ExaminerContacted</summary>
        public const string ExaminerContacted = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-examiner-contacted";

        /// <summary>URL for CodingStatusValues</summary>
        public const string CodingStatusValues = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coding-status-values";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public const string WithinCityLimitsIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/WithinCityLimitsIndicator";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public const string DecedentDispositionMethod = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-disposition-method";

        /// <summary>URL for Decedent</summary>
        public const string Decedent = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent";

        /// <summary>URL for PlaceOfInjury</summary>
        public const string PlaceOfInjury = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-place-of-injury";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DistrictCode";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public const string EntityAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-entity-axis-cause-of-death";

        /// <summary>URL for DeathLocation</summary>
        public const string DeathLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-location";

        /// <summary>URL for DateDay</summary>
        public const string DateDay = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Day";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDate";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public const string ManualUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manual-underlying-cause-of-death";

        /// <summary>URL for DecedentTransportationRole</summary>
        public const string DecedentTransportationRole = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-transportation-role";

        /// <summary>URL for FuneralHome</summary>
        public const string FuneralHome = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-funeral-home";

        /// <summary>URL for SpouseAlive</summary>
        public const string SpouseAlive = "http://hl7.org/fhir/us/vrdr/StructureDefinition/SpouseAlive";

        /// <summary>URL for DeathCertificate</summary>
        public const string DeathCertificate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate";

        /// <summary>URL for FilingFormat</summary>
        public const string FilingFormat = "http://hl7.org/fhir/us/vrdr/StructureDefinition/FilingFormat";

        /// <summary>URL for DateTime</summary>
        public const string DateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Time";

        /// <summary>URL for DecedentSpouse</summary>
        public const string DecedentSpouse = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-spouse";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PostDirectional";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public const string CauseOfDeathPart1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part1";

        /// <summary>URL for DecedentMother</summary>
        public const string DecedentMother = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-mother";

        /// <summary>URL for StateSpecificField</summary>
        public const string StateSpecificField = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StateSpecificField";

        /// <summary>URL for AuxiliaryStateIdentifier2</summary>
        public const string AuxiliaryStateIdentifier2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier2";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CityCode";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetName";

        /// <summary>URL for InjuryIncident</summary>
        public const string InjuryIncident = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-incident";

        /// <summary>URL for DeathCertificateDocument</summary>
        public const string DeathCertificateDocument = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate-document";

        /// <summary>URL for InjuryLocation</summary>
        public const string InjuryLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-location";

        /// <summary>URL for DeathCertification</summary>
        public const string DeathCertification = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certification";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Location-Jurisdiction-Id";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public const string AutopsyPerformedIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-autopsy-performed-indicator";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public const string CodedRaceAndEthnicity = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coded-race-and-ethnicity";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public const string AutomatedUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-automated-underlying-cause-of-death";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetNumber";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public const string DecedentPregnancyStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-pregnancy-status";

        /// <summary>URL for InjuryLocationReference</summary>
        public const string InjuryLocationReference = "http://hl7.org/fhir/us/vrdr/StructureDefinition/InjuryLocationReference";

        /// <summary>URL for DecedentUsualWork</summary>
        public const string DecedentUsualWork = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-usual-work";

        /// <summary>URL for DispositionLocation</summary>
        public const string DispositionLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-disposition-location";

        /// <summary>URL for DateMonth</summary>
        public const string DateMonth = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Month";

        /// <summary>URL for Certifier</summary>
        public const string Certifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-certifier";

        /// <summary>URL for DeathLocationReference</summary>
        public const string DeathLocationReference = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DeathLocationReference";

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public const string ActivityAtTimeOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-activity-at-time-of-death";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public const string RecordAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-record-axis-cause-of-death";

    }
}
