// DO NOT EDIT MANUALLY! This file was generated by the script "tools/generate_url_strings_from_VRDR_IG.rb"

namespace VRDR
{
    /// <summary>Profile URLs</summary>
    public static class ProfileURL
    {
        /// <summary>URL for DeathDate</summary>
        public const string DeathDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-date";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public const string BirthRecordIdentifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-birth-record-identifier";

        /// <summary>URL for DecedentMilitaryService</summary>
        public const string DecedentMilitaryService = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-military-service";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public const string TobaccoUseContributedToDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-tobacco-use-contributed-to-death";

        /// <summary>URL for DecedentAge</summary>
        public const string DecedentAge = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-age";

        /// <summary>URL for MannerOfDeath</summary>
        public const string MannerOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manner-of-death";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public const string InputRaceAndEthnicity = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-input-race-and-ethnicity";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public const string CauseOfDeathPart2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part2";

        /// <summary>URL for DecedentFather</summary>
        public const string DecedentFather = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-father";

        /// <summary>URL for DecedentEducationLevel</summary>
        public const string DecedentEducationLevel = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-education-level";

        /// <summary>URL for SurgeryDate</summary>
        public const string SurgeryDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-surgery-date";

        /// <summary>URL for EmergingIssues</summary>
        public const string EmergingIssues = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-emerging-issues";

        /// <summary>URL for ExaminerContacted</summary>
        public const string ExaminerContacted = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-examiner-contacted";

        /// <summary>URL for CodingStatusValues</summary>
        public const string CodingStatusValues = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coding-status-values";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public const string DecedentDispositionMethod = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-disposition-method";

        /// <summary>URL for Decedent</summary>
        public const string Decedent = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent";

        /// <summary>URL for PlaceOfInjury</summary>
        public const string PlaceOfInjury = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-place-of-injury";

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public const string CauseOfDeathCodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-coded-bundle";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public const string EntityAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-entity-axis-cause-of-death";

        /// <summary>URL for DeathLocation</summary>
        public const string DeathLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-location";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public const string ManualUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manual-underlying-cause-of-death";

        /// <summary>URL for FuneralHome</summary>
        public const string FuneralHome = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-funeral-home";

        /// <summary>URL for DeathCertificate</summary>
        public const string DeathCertificate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate";

        /// <summary>URL for DecedentSpouse</summary>
        public const string DecedentSpouse = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-spouse";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public const string CauseOfDeathPart1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part1";

        /// <summary>URL for DecedentMother</summary>
        public const string DecedentMother = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-mother";

        /// <summary>URL for InjuryIncident</summary>
        public const string InjuryIncident = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-incident";

        /// <summary>URL for DeathCertificateDocument</summary>
        public const string DeathCertificateDocument = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate-document";

        /// <summary>URL for InjuryLocation</summary>
        public const string InjuryLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-location";

        /// <summary>URL for DeathCertification</summary>
        public const string DeathCertification = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certification";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public const string AutopsyPerformedIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-autopsy-performed-indicator";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public const string CodedRaceAndEthnicity = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coded-race-and-ethnicity";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public const string AutomatedUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-automated-underlying-cause-of-death";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public const string DecedentPregnancyStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-pregnancy-status";

        /// <summary>URL for DecedentUsualWork</summary>
        public const string DecedentUsualWork = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-usual-work";

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public const string DemographicCodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-demographic-coded-bundle";

        /// <summary>URL for DispositionLocation</summary>
        public const string DispositionLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-disposition-location";

        /// <summary>URL for Certifier</summary>
        public const string Certifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-certifier";

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public const string ActivityAtTimeOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-activity-at-time-of-death";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public const string RecordAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-record-axis-cause-of-death";

        /// <summary>URL for MortalityRosterBundle </summary>
        public const string MortalityRosterBundle = "http://hl7.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-mortality-roster-bundle";

    }

    /// <summary>Extension URLs</summary>
    public static class ExtensionURL
    {
        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/UnitOrAptNumber";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetDesignator";

        /// <summary>URL for BypassEditFlag</summary>
        public const string BypassEditFlag = "http://hl7.org/fhir/us/vrdr/StructureDefinition/BypassEditFlag";

        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDateTime";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public const string NVSSSexAtDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/NVSS-SexAtDeath";

        /// <summary>URL for DateYear</summary>
        public const string DateYear = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Year";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PreDirectional";

        /// <summary>URL for AuxiliaryStateIdentifier1</summary>
        public const string AuxiliaryStateIdentifier1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier1";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public const string WithinCityLimitsIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/WithinCityLimitsIndicator";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DistrictCode";

        /// <summary>URL for DateDay</summary>
        public const string DateDay = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Day";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDate";

        /// <summary>URL for SpouseAlive</summary>
        public const string SpouseAlive = "http://hl7.org/fhir/us/vrdr/StructureDefinition/SpouseAlive";

        /// <summary>URL for FilingFormat</summary>
        public const string FilingFormat = "http://hl7.org/fhir/us/vrdr/StructureDefinition/FilingFormat";

        /// <summary>URL for DateTime</summary>
        public const string DateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Time";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PostDirectional";

        /// <summary>URL for StateSpecificField</summary>
        public const string StateSpecificField = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StateSpecificField";

        /// <summary>URL for AuxiliaryStateIdentifier2</summary>
        public const string AuxiliaryStateIdentifier2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier2";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CityCode";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetName";

        /// <summary>URL for CertificateNumber</summary>
        public const string CertificateNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CertificateNumber";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Location-Jurisdiction-Id";

        /// <summary>URL for ReplaceStatus</summary>
        public const string ReplaceStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/ReplaceStatus";

        /// <summary>URL for AliasStatus</summary>
        public const string AliasStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AliasStatus";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetNumber";

        /// <summary>URL for DateMonth</summary>
        public const string DateMonth = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Month";

    }

    /// <summary>IG URLs</summary>
    public static class IGURL
    {
        /// <summary>URL for DeathDate</summary>
        public const string DeathDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-date.html";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public const string BirthRecordIdentifier = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-birth-record-identifier.html";

        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-UnitOrAptNumber.html";

        /// <summary>URL for DecedentMilitaryService</summary>
        public const string DecedentMilitaryService = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-military-service.html";

        /// <summary>URL for CauseOfDeathPathway</summary>
        public const string CauseOfDeathPathway = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-pathway.html";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetDesignator.html";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public const string TobaccoUseContributedToDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-tobacco-use-contributed-to-death.html";

        /// <summary>URL for DecedentAge</summary>
        public const string DecedentAge = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-age.html";

        /// <summary>URL for BypassEditFlag</summary>
        public const string BypassEditFlag = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-BypassEditFlag.html";

        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PartialDateTime.html";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public const string NVSSSexAtDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-NVSS-SexAtDeath.html";

        /// <summary>URL for MannerOfDeath</summary>
        public const string MannerOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-manner-of-death.html";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public const string InputRaceAndEthnicity = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-input-race-and-ethnicity.html";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public const string CauseOfDeathPart2 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-part2.html";

        /// <summary>URL for DateYear</summary>
        public const string DateYear = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Year.html";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PreDirectional.html";

        /// <summary>URL for DecedentFather</summary>
        public const string DecedentFather = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-father.html";

        /// <summary>URL for DecedentEducationLevel</summary>
        public const string DecedentEducationLevel = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-education-level.html";

        /// <summary>URL for AuxiliaryStateIdentifier1</summary>
        public const string AuxiliaryStateIdentifier1 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-AuxiliaryStateIdentifier1.html";

        /// <summary>URL for SurgeryDate</summary>
        public const string SurgeryDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-surgery-date.html";

        /// <summary>URL for EmergingIssues</summary>
        public const string EmergingIssues = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-emerging-issues.html";

        /// <summary>URL for ExaminerContacted</summary>
        public const string ExaminerContacted = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-examiner-contacted.html";

        /// <summary>URL for CodingStatusValues</summary>
        public const string CodingStatusValues = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-coding-status-values.html";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public const string WithinCityLimitsIndicator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-WithinCityLimitsIndicator.html";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public const string DecedentDispositionMethod = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-disposition-method.html";

        /// <summary>URL for Decedent</summary>
        public const string Decedent = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent.html";

        /// <summary>URL for PlaceOfInjury</summary>
        public const string PlaceOfInjury = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-place-of-injury.html";

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public const string CauseOfDeathCodedContentBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-coded-bundle.html";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-DistrictCode.html";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public const string EntityAxisCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-entity-axis-cause-of-death.html";

        /// <summary>URL for DeathLocation</summary>
        public const string DeathLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-location.html";

        /// <summary>URL for DateDay</summary>
        public const string DateDay = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Day.html";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PartialDate.html";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public const string ManualUnderlyingCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-manual-underlying-cause-of-death.html";

        /// <summary>URL for FuneralHome</summary>
        public const string FuneralHome = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-funeral-home.html";

        /// <summary>URL for SpouseAlive</summary>
        public const string SpouseAlive = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-SpouseAlive.html";

        /// <summary>URL for DeathCertificate</summary>
        public const string DeathCertificate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certificate.html";

        /// <summary>URL for FilingFormat</summary>
        public const string FilingFormat = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-FilingFormat.html";

        /// <summary>URL for DateTime</summary>
        public const string DateTime = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Time.html";

        /// <summary>URL for DecedentSpouse</summary>
        public const string DecedentSpouse = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-spouse.html";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PostDirectional.html";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public const string CauseOfDeathPart1 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-part1.html";

        /// <summary>URL for DecedentMother</summary>
        public const string DecedentMother = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-mother.html";

        /// <summary>URL for StateSpecificField</summary>
        public const string StateSpecificField = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StateSpecificField.html";

        /// <summary>URL for AuxiliaryStateIdentifier2</summary>
        public const string AuxiliaryStateIdentifier2 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-AuxiliaryStateIdentifier2.html";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-CityCode.html";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetName.html";

        /// <summary>URL for InjuryIncident</summary>
        public const string InjuryIncident = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-injury-incident.html";

        /// <summary>URL for DeathCertificateDocument</summary>
        public const string DeathCertificateDocument = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certificate-document.html";

        /// <summary>URL for InjuryLocation</summary>
        public const string InjuryLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-injury-location.html";

        /// <summary>URL for DeathCertification</summary>
        public const string DeathCertification = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certification.html";

        /// <summary>URL for CertificateNumber</summary>
        public const string CertificateNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-CertificateNumber.html";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Location-Jurisdiction-Id.html";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public const string AutopsyPerformedIndicator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-autopsy-performed-indicator.html";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public const string CodedRaceAndEthnicity = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-coded-race-and-ethnicity.html";

        /// <summary>URL for ReplaceStatus</summary>
        public const string ReplaceStatus = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-ReplaceStatus.html";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public const string AutomatedUnderlyingCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-automated-underlying-cause-of-death.html";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetNumber.html";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public const string DecedentPregnancyStatus = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-pregnancy-status.html";

        /// <summary>URL for DecedentUsualWork</summary>
        public const string DecedentUsualWork = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-usual-work.html";

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public const string DemographicCodedContentBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-demographic-coded-bundle.html";

        /// <summary>URL for DispositionLocation</summary>
        public const string DispositionLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-disposition-location.html";

        /// <summary>URL for DateMonth</summary>
        public const string DateMonth = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Month.html";

        /// <summary>URL for Certifier</summary>
        public const string Certifier = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-certifier.html";

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public const string ActivityAtTimeOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-activity-at-time-of-death.html";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public const string RecordAxisCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-record-axis-cause-of-death.html";

        /// <summary>URL for MortalityRosterBundle </summary>
        public const string MortalityRosterBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-mortality-roster-bundle.html";
    }
}
