// DO NOT EDIT MANUALLY! This file was generated by the script "generate_value_set_lookups_from_VRDR_IG.rb"

namespace VRDR
{
    /// <summary> ValueSet Helpers </summary>
    public static class ValueSets
    {
        /// <summary> AdministrativeGender </summary>
        public static class AdministrativeGender {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "male", "Male", VRDR.CodeSystems.AdministrativeGender },
                { "female", "Female", VRDR.CodeSystems.AdministrativeGender },
                { "unknown", "unknown", VRDR.CodeSystems.AdministrativeGender }
            };
            /// <summary> Male </summary>
            public static string  Male = "male";
            /// <summary> Female </summary>
            public static string  Female = "female";
            /// <summary> Unknown </summary>
            public static string  Unknown = "unknown";
        };
        /// <summary> BirthplaceCountry </summary>
        public static class BirthplaceCountry {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
