name: update documentation
on:
  push:
    branches:
      - master # Default release branch
jobs:
  docs:
    name: Build and push doxygen documentation to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build using Doxygen
        uses: mattnotmitt/doxygen-action@v1
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
